apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canfar-storage-ui-integration
  namespace: argocd
  labels:
    argocd.argoproj.io/domain: canfar.net
    argocd.argoproj.io/environment: integration
    argocd.argoproj.io/service: storage-ui
spec:
  project: default
  sources:
    - repoURL: oci://harbor.example.com/canfar/charts
      chart: storageui
      targetRevision: 0.9.0
      helm:
        valueFiles:
          - $values/helm/values/canfar.net/storage-ui/base.yaml
          - $values/helm/values/canfar.net/storage-ui/integration.yaml
    - repoURL: https://git.example.com/your-org/argo-deploy.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: canfar-storage-ui-integration
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
