apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canfar-storage-ui-prod
  namespace: canfar-argocd
  labels:
    argocd.argoproj.io/domain: canfar.net
    argocd.argoproj.io/environment: production
    argocd.argoproj.io/service: storage-ui
spec:
  project: canfar
  sources:
    - repoURL: https://images.opencadc.org/chartrepo/client
      chart: storageui
      targetRevision: 1.4.5
      helm:
        valueFiles:
          - $values/helm/values/canfar.net/storage-ui/base.yaml
          - $values/helm/values/canfar.net/storage-ui/prod.yaml
    - repoURL: https://github.com/cadc-ccda-infra/keel-deploy.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: canfar-system-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
