global:
  minikube: false
  retry:
    - "--tries=10"
    - "--sleep=5"

labels:
  app: ska-src-dm-local-data-preparer

annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG

localPreparerCore:
  image:
    registry: artefact.skao.int
    image: ska-src-dm-local-data-preparer
    tag: 0.2.1
    pullPolicy: Always

  # Node labels for pod assignment of the data preparer core
  # ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  nodeSelector: {}

  # Affinity settings of the data preparer core
  # ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

celeryWorker:
  image:
    registry: artefact.skao.int
    image: ska-src-dm-local-data-preparer-celery
    tag: 0.2.1
    pullPolicy: Always

  # This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
  serviceAccount: {}

  # Security context for the pod.
  # ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  podSecurityContext: {}
    # fsGroup: 2000

  # Container security context.
  # ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  # Node labels for pod assignment
  # ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  nodeSelector: {}

  # Affinity settings
  # ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

# Allow the deployer to NOT specify a spec.type value, and leave it up to the Kubernetes Cluster to determine type.
# The default NodePort is set here to maintain the existing value.
#
# Examples:
### Specify ClusterIP type:
#  service:
#    type: ClusterIP
#
### Omit type:
#  service:
#    type:
service:
  type: NodePort
  port: 8000

rabbitmqService:
  port: 5672
  managementPort: 15672

  # The Cluster Domain this is running in.  It's used to build the URL for the Celery and Core services.
  domain: "cluster.local"

  # Type of the service to use.  Set the NodePort here for consistency with existing deployment.
  # Examples:
  ### Specify ClusterIP type:
  #  type: ClusterIP
  #
  ### Omit type:
  #  type:
  type: NodePort

  # This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
  serviceAccount: {}

  # Security context for the pod.
  # ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  podSecurityContext: {}
    # fsGroup: 2000

  # Container security context.
  # ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  # Node labels for pod assignment
  # ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  nodeSelector: {}

  # Affinity settings
  # ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount: {}

# Security context for the pod.
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
podSecurityContext: {}
  # fsGroup: 2000

# Container security context.
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# Node labels for pod assignment
# ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
nodeSelector: {}

# Affinity settings
# ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

env:
  PREPARE_DATA_APPROACH: copy_to_user_area
  ABS_PATH_USER_AREA_ROOT: /users/cavern/home
  ABS_PATH_RSE_ROOT: /rse_data/deterministic
  ABS_PATH_CELERY_RESULTS: /var/celery/results

pvc:
  rse: "rse-pvc"
  rsePath: "/rse_data"
  cavern: "cavern-pvc"
  cavernPath: "/users/cavern/home"
  celeryCache: "celery-pvc"
  celeryCachePath: "/var/celery/results"
