apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xrootd-pvc
  namespace: canfar-src-staging
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: cephfs-legacy-src-staging-xrootd-pv
