# Shared defaults for Storage UI (opencadc client chart).  Hostname and OIDC redirect/callback URIs: prod.yaml / staging.yaml.

kubernetesClusterDomain: keel-prod.local

replicaCount: 1

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 8675309
  runAsGroup: 8675309
  fsGroup: 8675309
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  privileged: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault

deployment:
  storageUI:
    registryURL:
      - "https://spsrc27.iaa.csic.es/reg"
      - "https://reg.swesrc.chalmers.se"

    theme:
      name: src
      logoURL: https://staging-src.canfar.net/science-portal/images/canSRCLogo.png

    gmsID: ivo://skao.int/gms

    backend:
      defaultService: cavern
      services:
        cavern:
          resourceID: "ivo://canfar.net/staging-src/cavern"
          nodeURIPrefix: "vos://canfar.net~staging-src~cavern"
          userHomeDir: "/home"
          features:
            batchDownload: true
            batchUpload: false
            externalLinks: false
            paging: false

    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "1500Mi"
        cpu: "750m"

    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 50
          preference:
            matchExpressions:
              - key: skaha.opencadc.org/node-type
                operator: In
                values:
                  - service-node
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nvidia.com/gpu.count
                operator: DoesNotExist

secrets: {}

redis:
  networkPolicy:
    enabled: false
  serviceAccount:
    create: false
  architecture: standalone
  auth:
    enabled: false
  master:
    serviceAccount:
      create: false
    persistence:
      enabled: false
