deployment:
  hostname: staging-src.canfar.net
  storageUI:
    oidc:
      redirectURI: https://staging-src.canfar.net/storage/oidc-callback
      callbackURI: https://staging-src.canfar.net/storage/list
