apiVersion: v1
kind: Secret
metadata:
  name: ac-ldap-config
  namespace: cadc-system-production
  labels:
    cadc.dao.nrc.ca/component: ac
stringData:
  proxyPassword: ah340dNK8v
---
apiVersion: v1
kind: Secret
metadata:
  name: ac-oidc-signing-keys
  namespace: cadc-system-production
  labels:
    cadc.dao.nrc.ca/component: ac
stringData:
  oidc-rsa256-pub.key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsc73IJCnuaob7BB1JlWnDbkwMe7B5VsG
    KXSXO9HxtI+DaYjwc9LNRpIq+x4N3biN1cknat+ZBjYoWgWpT4KBZvNd1f8hQM+9BqDcEgwoQL8D
    otYiZJ0trvba/BC8wOwNNbMrUT+mHkba3lqb3jJNgRf5NXmIL1BbmtoB3jepi1q48ZQK+Njt7KFL
    UjwgsmYvPQ0BYjYE0iU9qD+JwWJrlrjitx4qM/XiWjNNOW/hbIZqtjNh6EN0KytwHWLKsZouPyH3
    +MzSD6Se7N5JAQ1/J5OFlAB+CHFLbylSd6/6Pi3zSm3t3xXJ+61kDHnscYlbRea0e7+b00z5a2tS
    vcQ/cQIDAQAB
    -----END PUBLIC KEY-----
  oidc-rsa256-priv.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCxzvcgkKe5qhvsEHUmVacNuTAx
    7sHlWwYpdJc70fG0j4NpiPBz0s1Gkir7Hg3duI3VySdq35kGNihaBalPgoFm813V/yFAz70GoNwS
    DChAvwOi1iJknS2u9tr8ELzA7A01sytRP6YeRtreWpveMk2BF/k1eYgvUFua2gHeN6mLWrjxlAr4
    2O3soUtSPCCyZi89DQFiNgTSJT2oP4nBYmuWuOK3Hioz9eJaM005b+Fshmq2M2HoQ3QrK3AdYsqx
    mi4/Iff4zNIPpJ7s3kkBDX8nk4WUAH4IcUtvKVJ3r/o+LfNKbe3fFcn7rWQMeexxiVtF5rR7v5vT
    TPlra1K9xD9xAgMBAAECggEAMdyB/IXUIwKK9fXfhDJ8uCJ4W2hCw1h1L+bcChBjoWilR1D5bOFu
    Yx3WI7lX1hdM3uibvyKYvN8vDZ+MzRkhxIb2h24WGyCmN1egnwb9urpWALHfzysshmX/HrRq2gbX
    5Xkq6ovYv6DK+5OZJgQhK9RXNCGyiOIV7iS4ZWJijwsWwPJh9PPgl9Zxp4PZB0+vCw6c68/5dQi6
    DqrqHVRzgWsYvuiK8/tiQiP+B/yCAArWEpCx7aIdojqyogE3TUBizSYFc787A+EAuz8dOR2dpaAI
    74l8EuQ99IYiQTKfU+PDxtBlvy4I/02ILIV7x0IPN95q7/xmnJa8410Ea7+IAQKBgQD442YQHquM
    MXFRzlEfOx/ByYRUXXD6v397Nr0tjItCItwMZI744RgV83CV/2iFPcpBJ9gIv1qHaQAa/tGI6l0X
    M4+EmlT3HG3YJ49kappC7setx3SmqCrO/CzFCfCsIc1aDywrzNWHjHDq5yvC5oZSrBhghvstX0E6
    Acupga3hwQKBgQC2459a5JI2FFnTmWeOuYrtygrHkA3fvYjTh5aTQM/oJugXEVKSktOuoFetcsVV
    YJBWgGqbvTuQ5rdXgWom6lFmFrtzihYkSdQeKYVEloWjwgk8vVREaZqU9GuIkAetMBYps8YxoE8i
    S0MqsWMbvgZQeqLpaonHc0ZfBIXzKbNpsQKBgQCEf0KRaFJ5EsU6ALTtBGO2nZol84y24IV0ScLS
    YdStA7PToSD/240f+nZAVDUHYcqvfw+iMIR4O+zDck6ILgQa2ucXd7Wty+OqQ/0xPxMaeNWybNFr
    +3C2ukb3KoCGkoQo4pToSGaQf7KJS0HfwytVDar4kENddy1ZPSV3+sJfwQKBgQCNQA/7az1hdyZJ
    Ptm0aajbLohUyPVuMDxU4wtwf0YTzrjB2Ccl/TBwVnZhB5tQ7VuM83FjByvSJd7EPrd1htOHPVdZ
    TPT84ehpwzeiWX6tk1b/Clri240ALiY/Or4zDEiRvL795Qo5OleNyaL58jF+Rrk7/YSb/nQDPsMV
    osdmgQKBgBnLkGPauQ6cEvD4elarK/usq4Sy8wc4jxioJdS8GdeFTysnHmCAQupnqCC6T0GJ1D47
    SXViSKXJJd4XmLLKPvud8se9mEekm8ZyMw3YTr9PAlponsgXk3F4wKda5B4qghcWtvJ1yD+fnZgI
    R09gOXBG9INt4DGJgsSn7dDoW6+x
    -----END PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: ac-oidc-opencadc-harbor
  namespace: cadc-system-production
  labels:
    cadc.dao.nrc.ca/component: ac
stringData:
  secret: 0penC4DC
---
apiVersion: v1
kind: Secret
metadata:
  name: ac-oidc-arbutus-harbor
  namespace: cadc-system-production
  labels:
    cadc.dao.nrc.ca/component: ac
stringData:
  secret: harbor-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: ac-oidc-unions-wiki
  namespace: cadc-system-production
  labels:
    cadc.dao.nrc.ca/component: ac
stringData:
  secret: MkpmK6ch
---
apiVersion: v1
kind: Secret
metadata:
  name: ac-oidc-ossos-wiki
  namespace: cadc-system-production
  labels:
    cadc.dao.nrc.ca/component: ac
stringData:
  secret: xsMGZQyP
---
apiVersion: v1
kind: Secret
metadata:
  name: ac-oidc-unions-sky-browser
  namespace: cadc-system-production
  labels:
    cadc.dao.nrc.ca/component: ac
stringData:
  secret: 76SBtZ7F
---
apiVersion: v1
kind: Secret
metadata:
  name: ac-oidc-candiapl
  namespace: cadc-system-production
  labels:
    cadc.dao.nrc.ca/component: ac
stringData:
  secret: C4nD14pL
---
apiVersion: v1
kind: Secret
metadata:
  name: cookie-signature-private-key
  namespace: cadc-system-production
  labels:
    cadc.dao.nrc.ca/component: ac
stringData:
  RsaSignaturePriv.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC+K3CCH31SUtM1SBlYrLdsMH67
    v75Bf+Ialvcf+nSjR0JC6s4cf01JaRQf2mjQIOcMZM3RkWgtR4YEMOX+kI3YuT4BibHuyPFRjtiI
    8DqJcrXMtC0+opkL+hnsKoXanJRmhJjpj/GPtBvMVOEVH6YLt1e0/QaK7aXzvBizM1QDNJsAC7J+
    aaKkSNNB989MBn5BdjkmKV1Lvz/g6IEw7eug7IjK4Bqz2Q3giL69lg7CpcyNACEwExXObtbBD5rq
    nVfjeZhGQqSYtj8e1LM3wJj9joEXkKoeAgh5zD14NVVI3evvVllZHq/FbJnJ3k2I7Gd5Ko/SsBMb
    e7xMT48hJALvAgMBAAECggEAeay5k8gqGx47XQAAl6gKxAJTVDVeufHk7TZib+eD8WSKlN4/eiRJ
    gwrkgWzxWxlyO4/T0J7ElRQKP2w5/CLpXx1G+xzq5+lR3ekTyqpKCd+HSq6NtGG8otkm9OBQPIuq
    t91nKSmcWWHX12kHishxKVXpnDe4k/NyFvzmoOHagyFu1kZ6M3Q4D4CeR6SRamEiEY/cfEBYNCRQ
    aUQt0IFde8WPp1LpHhq2ZIh2xJKVMuDGVxPiMoRh40aABs87HdpV7rMwM+UngQrzTxrYVA9642ex
    E4s0WIPQ37C1AGtKiohdozjWR2GPMjS7BnwDLVemMTL7N2Ascw1P1SUyp9+/gQKBgQDm9d4QXFdV
    uJG/8xkzXeLY64+ogW5yY+8NTClN66PMvffpEvy7OqE0ldSdnc2GqE+IPT28LYbbc6txhubebvgq
    rbArJXPdzsejopn9lrWCkbVQX6BqXrdaxtkxNdklw56PcTqerGbmG+AEky9tswRuEbzyoDrWNsCp
    sixF/Th/nwKBgQDSyXS37cW+xVJtfcnSIC+JL8r7Vf5QvGo22FCUwMn5ZOcfdNzZmBxyKy8Kv6fx
    o6pv1Gwb9B+5qSBR1E5IgOMCtk4VyBqt15Fw6GYh8M1C5dZhBuNhTX3B+JZFLS+NIzS2glFlciJX
    0L6WqMHQhAHKHuqk+QySnTeAerPOsH56sQKBgQCrT6WmVwgEskGRshx4KGSR57AIGfE1cgCnyV09
    ydIWlLXlMMs7iRJ3scciHiGLhx5u/JXlFZPZBSQesiReysrSxUBN0Jrv5GfabUpxea8qqS9m7XdM
    TvMLp0EEql9mDoJ2/VKwzUoJ1pVEb3QXl1hq2EdhZA4gRD6F4H3McDXPGwKBgQDKeduVZmBCLTdN
    l7wLDQG8jN01atg845A/mLBnA33AA84DqHUQy43fmV25vHptoiJxA6LJg0oKRMyX7hE4kh3+F/KP
    98Sw4taBl6urxKzXKwIv97bpW8+GSOzIDGyV7ZCQFERt5yHYKts4y2hJjNRPPD13NQh/uWd8EeGw
    lFcaMQKBgQCuiJs6CiLq+2739nldf8kOXmUNkkzkcG+HXqrclwldtEDhi3h7Ub0DZJakKt/Menss
    flebF2NeSoNSQNT+pAzhcpSxKSJyQ6j2hOBocSlbzbJEv89SIDN9kT5y2OJW46RS8s78RUGhGsyf
    8zAvrnSxw3kLN1uXmqVOfXfOnW5R7Q==
    -----END PRIVATE KEY-----
---