apiVersion: v1
kind: Secret
metadata:
  name: bucket-registry-creds
  namespace: canfar-argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  name: bucket-registry-creds
  type: oci
  url: oci://bucket.canfar.net
  username: jenkinsd
  password: del0rean
  enableOCI: "true"
  enableHttpBasicAuth: "true"
