# Resource Flavors
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: default
spec:
  nodeLabels:
    skaha.opencadc.org/node-type: worker-node
    skaha.opencadc.org/node-type: gpu-node
