apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: celery-worker
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      {{- with .Values.celeryWorker.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "api.serviceAccountName" .Values.celeryWorker }}
      containers:
      - name: ska-src-local-data-preparer-celery-worker
        {{- with .Values.celeryWorker.securityContext }}
        securityContext:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        image: "{{ .Values.celeryWorker.image.registry }}/{{ .Values.celeryWorker.image.image }}:{{ .Values.celeryWorker.image.tag }}"
        imagePullPolicy: {{ .Values.celeryWorker.image.pullPolicy }}
        env:
          - name: CELERY_BROKER_URL
            value: "amqp://guest@rabbitmq.{{ .Release.Namespace }}.svc.{{ .Values.rabbitmqService.domain }}//"
          - name: ABS_PATH_CELERY_RESULTS
            value: "{{ .Values.env.ABS_PATH_CELERY_RESULTS }}"
        command: ["celery", "-A", "src.prepare_data.tasks", "worker", "--loglevel=info", "-c", "1"]
        volumeMounts:
          - name: rse
            mountPath: "{{ .Values.pvc.rsePath }}"
          - name: cavern
            mountPath: "{{ .Values.pvc.cavernPath }}"
          - name: celery-cache
            mountPath: "{{ .Values.pvc.celeryCachePath }}"
      {{- with .Values.celeryWorker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.celeryWorker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: rse
          persistentVolumeClaim:
            claimName: "{{ .Values.pvc.rse }}"
        - name: cavern
          persistentVolumeClaim:
            claimName: "{{ .Values.pvc.cavern }}"
        - name: celery-cache
          persistentVolumeClaim:
            claimName: "{{ .Values.pvc.celeryCache }}"
