apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      {{- with .Values.rabbitmqService.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "api.serviceAccountName" .Values.rabbitmqService }}
      containers:
      - name: ska-src-local-data-preparer-rabbitmq
        {{- with .Values.rabbitmqService.securityContext }}
        securityContext:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        image: rabbitmq:3.12-management
        ports:
          - containerPort: 5672
      {{- with .Values.rabbitmqService.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rabbitmqService.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
