apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: celery-cache-pvc
  namespace: canfar-src-production
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: general
  volumeMode: Filesystem
