---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-traefik-ingress
  namespace: canfar-src-production
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "false"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  rules:
  - host: src.canfar.net
    http:
      paths:
      - path: /echo
        pathType: Prefix
        backend:
          service:
            name: ska-src-dm-da-service-gatekeeper
            port:
              number: 80
