# Staging overlay — LDAP pool sizes and hosts from cadc-rc ac,
# exposed on staging-cadc-west-01.canfar.net.

image:
  repository: at88mph/ac
  pullPolicy: Always
  tag: SNAPSHOT

ingress:
  hosts:
    - host: staging-cadc-west-01.canfar.net
      paths:
        - path: /ac
          pathType: Prefix

imagePullSecrets:
  - name: bucket-registry-auth

replicaCount: 1

resources:
  requests:
    cpu: 750m
    memory: 3000Mi
  limits:
    cpu: 2500m
    memory: 4000Mi

extraHosts:
  - hostname: quokka.canfar.internal
    ip: 206.12.48.218

application:
  registryURL: https://staging-cadc-west-01.canfar.net/reg

  ldap:
    port: 10636
    readOnly:
      servers: quokka.canfar.internal
      poolInitSize: 10
      poolMaxSize: 75
      secure: true
      port: 10636
    readWrite:
      servers: quokka.canfar.internal
      poolInitSize: 5
      poolMaxSize: 25
      secure: true
      port: 10636
    unboundReadOnly:
      servers: quokka.canfar.internal
      poolInitSize: 5
      poolMaxSize: 25
      secure: true
      port: 10636
