apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sandbox-argus-prod
  namespace: cadc-sandbox
  labels:
    argocd.argoproj.io/domain: sc2.canfar.net
    argocd.argoproj.io/environment: production
    argocd.argoproj.io/service: argus
spec:
  project: cadc
  sources:
    - repoURL: https://images.opencadc.org/chartrepo/platform
      chart: argus
      targetRevision: 0.10.0
      helm:
        valueFiles:
          - $values/helm/values/sandbox/argus/base.yaml
          - $values/helm/values/sandbox/argus/prod.yaml
    - repoURL: https://github.com/cadc-ccda-infra/keel-deploy.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cadc-sandbox
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
