ingress:
  hosts:
    - host: integration.canfar.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: canfar-web-portal-tls
      hosts:
        - integration.canfar.net
