replicaCount: 1

deployment:
  hostname: staging.canfar.net

  cavern:
    image: images.opencadc.org/platform/cavern:0.9.3
    imagePullPolicy: Always
    registryURL: https://staging.canfar.net/reg

    uws:
      db:
        install: false
        maxActive: 6
        url: "jdbc:postgresql://quokka.canfar.net:8601/arcdb"
        auth:
          existingSecret: arc-uws-db-auth
        # Postgres User default in the postgres:13 image
        runUID: 999

    # Other data to be included in the main ConfigMap of this deployment.
    # Of note, files that end in .key are special and base64 decoded.
    extraConfigData:
      # .key files are special and are base64 decoded.
      RsaSignaturePub.key: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2aXR3Z2g5OVVsTFROVWdaV0t5M2JEQit1NysrUVgvaQpHcGIzSC9wMG8wZENRdXJPSEg5TlNXa1VIOXBvMENEbkRHVE4wWkZvTFVlR0JERGwvcENOMkxrK0FZbXg3c2p4VVk3WWlQQTZpWEsxCnpMUXRQcUtaQy9vWjdDcUYycHlVWm9TWTZZL3hqN1FiekZUaEZSK21DN2RYdFAwR2l1Mmw4N3dZc3pOVUF6U2JBQXV5Zm1taXBFalQKUWZmUFRBWitRWFk1SmlsZFM3OC80T2lCTU8zcm9PeUl5dUFhczlrTjRJaSt2WllPd3FYTWpRQWhNQk1Wem03V3dRK2E2cDFYNDNtWQpSa0trbUxZL0h0U3pOOENZL1k2QkY1Q3FIZ0lJZWN3OWVEVlZTTjNyNzFaWldSNnZ4V3laeWQ1TmlPeG5lU3FQMHJBVEczdThURStQCklTUUM3d0lEQVFBQgotLS0tLUVORCBQVUJMSUMgS0VZLS0tLS0K

# Set these appropriately to match your Persistent Volume Claim labels.
storage:
  service:
    spec:
      cephfs:
        monitors:
        - 10.30.201.3:6789
        - 10.30.202.3:6789
        - 10.30.203.3:6789
        path: /volumes/_nogroup/054e398e-a08e-425e-9f7c-fc394362e38e
        user: keel-prod-admin
        secretRef:
          name: cephfs-cephx-admin-key
        readOnly: false