skahaWorkload:
  namespace: canfar-workload

replicaCount: 3

deployment:
  hostname: staging.canfar.net

  skaha:
    registryURL:
      - https://staging.canfar.net/reg

    sessions:
      kueue:
        rbac:
          create: true
        default:
          queueName: "skaha-local-queue"
          priorityClass: "high"
        headless:
          queueName: "skaha-local-queue"
          priorityClass: "low"