kubernetesClusterDomain: keel-prod.local

replicaCount: 3

deployment:
  hostname: staging.canfar.net

  skaha:
    registryURL:
      - https://staging.canfar.net/reg

    sessions:
      namespace: canfar-workloads
      userStorage:
        spec:
          cephfs:
            monitors:
            - 10.30.201.3:6789
            - 10.30.202.3:6789
            - 10.30.203.3:6789
            path: /volumes/_nogroup/054e398e-a08e-425e-9f7c-fc394362e38e
            user: keel-prod-admin
            secretRef:
              name: cephfs-cephx-admin-key
            readOnly: false
      kueue:
        rbac:
          create: true
        default:
          queueName: "cadc-default"
          priorityClass: "high"
        headless:
          queueName: "cadc-default"
          priorityClass: "low"