apiVersion: v1
kind: Service
metadata:
  labels:
    app: ska-src-dm-da-service-gatekeeper-echo
  name: ska-src-dm-da-service-gatekeeper-echo
  namespace: {{ .Values.echo.namespace.name }}
spec:
  {{- with .Values.echo.service }}
  {{- if .type}}
  type: {{ .type }}
  {{- end }}
  ports:
  - name: "{{ .port }}"
    port: {{ .port }}
    targetPort: {{ .port }}
    protocol: TCP
  {{- end }}
  selector:
    app: ska-src-dm-da-service-gatekeeper-echo
