{{- if not .Values.gatekeeper.siteCapabilities.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gatekeeper.siteCapabilities.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  client_id: {{ required "siteCapabilities.clientId is required when existingSecret=false"
    .Values.gatekeeper.siteCapabilities.clientId | b64enc | quote }}
  client_secret: {{ required "siteCapabilities.clientSecret is required when existingSecret=false"
    .Values.gatekeeper.siteCapabilities.clientSecret | b64enc | quote }}
{{- end }}