apiVersion: v1
kind: Service
metadata:
  name: ska-src-dm-da-service-gatekeeper
  namespace: {{ .Values.gatekeeper.namespace }}
  labels:
    app: ska-src-dm-da-service-gatekeeper
spec:
  type: ClusterIP
  selector:
    app: ska-src-dm-da-service-gatekeeper
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
