apiVersion: v1
kind: Secret
metadata:
  name: harbor-chartrepo-science-platform
  namespace: canfar-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: harbor-science-platform
  url: https://image.opencadc.org/chartrepo/platform
