apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: src-skaha
  namespace: canfar-argocd
  labels:
    argocd.argoproj.io/domain: src.canfar.net
    argocd.argoproj.io/environment: production
    argocd.argoproj.io/service: skaha
spec:
  project: canfar
  sources:
    - repoURL: https://images.opencadc.org/chartrepo/platform
      chart: skaha
      targetRevision: 1.5.2
      helm:
        valueFiles:
          - $values/helm/values/src.canfar.net/skaha/base.yaml
          - $values/helm/values/src.canfar.net/skaha/prod.yaml
    - repoURL: https://github.com/cadc-ccda-infra/keel-deploy.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: canfar-src-production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
