application:
  # Ensure OAI is disabled.
  authority: ""

  # Derived from IVOA Registry (reg) service entries in the reg-resource-caps.properties file.
  serviceEntries:
    - id: "ivo://cadc.nrc.ca/reg"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/capabilities"
    - id: "ivo://cadc.nrc.ca/cadc/minoc"
      url: "https://ws-cadc.canfar.net/minoc/capabilities"
    - id: "ivo://cadc.nrc.ca/cadc/luskan"
      url: "https://ws-cadc.canfar.net/luskan/capabilities"
    - id: "ivo://cadc.nrc.ca/uvic/minoc"
      url: "https://ws-uv.canfar.net/minoc/capabilities"
    - id: "ivo://cadc.nrc.ca/uvic/luskan"
      url: "https://ws-uv.canfar.net/luskan/capabilities"
    - id: "ivo://cadc.nrc.ca/sfu/minoc"
      url: "https://ws-sf.canfar.net/minoc/capabilities"
    - id: "ivo://cadc.nrc.ca/sfu/luskan"
      url: "https://ws-sf.canfar.net/luskan/capabilities"
    - id: "ivo://cadc.nrc.ca/lsst/minoc"
      url: "https://ws-uv.canfar.net/lsst/minoc/capabilities"
    - id: "ivo://cadc.nrc.ca/lsst/luskan"
      url: "https://ws-uv.canfar.net/lsst/luskan/capabilities"
    - id: "ivo://cadc.nrc.ca/global/baldur"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/baldur/capabilities"
    - id: "ivo://cadc.nrc.ca/global/luskan"
      url: "https://cadc-west-01.canfar.net/luskan/capabilities"
    - id: "ivo://cadc.nrc.ca/global/raven"
      url: "https://cadc-west-01.canfar.net/raven/capabilities"
    - id: "ivo://cadc.nrc.ca/argus"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/argus/capabilities"
    - id: "ivo://cadc.nrc.ca/caom2ops"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/caom2ops/capabilities"
    - id: "ivo://cadc.nrc.ca/cred"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/cred/capabilities"
    - id: "ivo://cadc.nrc.ca/data"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/data/capabilities"
    - id: "ivo://cadc.nrc.ca/resolver"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/cadc-target-resolver/capabilities"
    - id: "ivo://cadc.nrc.ca/sia"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/sia/capabilities"
    - id: "ivo://cadc.nrc.ca/caom25/argus"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/caom25/argus/capabilities"
    - id: "ivo://cadc.nrc.ca/caom25/torkeep"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/caom25/torkeep/capabilities"
    - id: "ivo://cadc.nrc.ca/ams"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/ams/capabilities"
    - id: "ivo://cadc.nrc.ca/ams/alma"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/ams/alma/capabilities"
    - id: "ivo://cadc.nrc.ca/ams/cfht"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/ams/cfht/capabilities"
    - id: "ivo://cadc.nrc.ca/ams/cirada"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/ams/cirada/capabilities"
    - id: "ivo://cadc.nrc.ca/ams/dao"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/ams/dao/capabilities"
    - id: "ivo://cadc.nrc.ca/ams/drao"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/ams/drao/capabilities"
    - id: "ivo://cadc.nrc.ca/ams/eao"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/ams/eao/capabilities"
    - id: "ivo://cadc.nrc.ca/ams/gemini"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/ams/gemini/capabilities"
    - id: "ivo://cadc.nrc.ca/ams/ngvs"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/ams/ngvs/capabilities"
    - id: "ivo://cadc.nrc.ca/ams/maq"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/ams/maq/capabilities"
    - id: "ivo://cadc.nrc.ca/ams/mast"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/ams/mast/capabilities"
    - id: "ivo://cadc.nrc.ca/ams/omm"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/ams/omm/capabilities"
    - id: "ivo://cadc.nrc.ca/ams/shared"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/ams/shared/capabilities"
    - id: "ivo://cadc.nrc.ca/doi"
      url: "https://ws-cadc.canfar.net/doi/capabilities"
    - id: "ivo://cadc.nrc.ca/gms"
      url: "https://ws-cadc.canfar.net/ac/capabilities"
    - id: "ivo://cadc.nrc.ca/ums"
      url: "https://ws-cadc.canfar.net/ac/capabilities"
    - id: "ivo://cadc.nrc.ca/vault"
      url: "https://cadc-west-01.canfar.net/vault/capabilities"
    - id: "ivo://cadc.nrc.ca/youcat"
      url: "https://ws-uv.canfar.net/youcat/capabilities"
    - id: "ivo://cadc.nrc.ca/rdoi"
      url: "https://ws-cadc.canfar.net/rdoi/capabilities"
    - id: "ivo://cadc.nrc.ca/skaha"
      url: "https://ws-uv.canfar.net/skaha/capabilities"
    - id: "ivo://cadc.nrc.ca/arc"
      url: "https://ws-uv.canfar.net/arc/capabilities"
    - id: "ivo://oats.inaf.it/gms"
      url: "http://gms01.oats.inaf.it/ac/capabilities"
    - id: "ivo://oats.inaf.it/cred"
      url: "http://gms01.oats.inaf.it/cred/capabilities"
    - id: "ivo://oats.inaf.it/vospace"
      url: "http://space01.oats.inaf.it/vospace/capabilities"
    - id: "ivo://unam.ens.edc/luskan"
      url: "https://taos2-edc01.astrosen.unam.mx/luskan/capabilities"
    - id: "ivo://unam.ens.edc/minoc"
      url: "https://taos2-edc01.astrosen.unam.mx/minoc/capabilities"
    - id: "ivo://mast.stsci.edu/caom2repo"
      url: "https://mast.stsci.edu/portal/ArchivePartner/meta-service/capabilities"
    - id: "ivo://cadc.nrc.ca/sc2repo"
      url: "https://sc2.canfar.net/sc2repo/capabilities"
    - id: "ivo://cadc.nrc.ca/sc2tap"
      url: "https://sc2.canfar.net/sc2tap/capabilities"
    - id: "ivo://cadc.nrc.ca/sc2links"
      url: "https://sc2.canfar.net/sc2links/capabilities"
    - id: "ivo://cadc.nrc.ca/sc2meta"
      url: "https://sc2.canfar.net/sc2meta/capabilities"
    - id: "ivo://cadc.nrc.ca/sc2soda"
      url: "https://sc2.canfar.net/sc2soda/capabilities"
    - id: "ivo://cadc.nrc.ca/AICO"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/APASS"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/APERO"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/ALMACA"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/BLAST"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/BNUNN"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/BRITE-Constellation"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/CFHT"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/CFHTMEGAPIPE"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/CFHTTERAPIX"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/CFHTUSER"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/CFHTWIRWOLF"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/CGPS"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/DAO"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/DAOCADC"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/DAOPLATES"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/DRAO"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/EUCLID"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/EUCLID_DR1"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/EUCLID.DR1"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/EUCLID.Q1"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/FUSE"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/GEMINI"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/GEMINICADC"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/GEMINIPROC"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/HSTHLA"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/IRIS"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/JCMT"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/JCMTLP"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/JCMTLS"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/LCO"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/LOTSS"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/LSST.DP1"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/MACHO"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/MOST"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/NEOSSAT"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/NGVS"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/OMM"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/POSSUM"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/RACS"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/SCUBA-LC"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/SPICE-RACS"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/SUBARUCADC"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/TAOSII"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/UKIRT"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/VGPS"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/VLASS"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/WALLABY"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/mirror/HST"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/mirror/JWST"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/capabilities"
    - id: "ivo://cadc.nrc.ca/mirror/TESS"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/maq/capabilities"
    - id: "ivo://cadc.nrc.ca/test/AICO"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/APERO"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/BRITE-Constellation"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/CFHT"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/CFHTMEGAPIPE"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/DAO"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/DAOCADC"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/DDO"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/DRAO"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/EUCLID"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/EUCLID_DR1"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/EUCLID.DR1"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/EUCLID.Q1"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/GEMINI"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/GEMINICADC"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/GEMINIPROC"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/HST"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/IRIS"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/LCO"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/LOTSS"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/LSST.DP1"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/OMM"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/PHANGS"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/POSSUM"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/VLASS"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/TAOSII"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/ALMACA"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/NEOSSAT"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/NGVS"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/RACS"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/SCUBA-LC"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/SPICE-RACS"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/SUBARUCADC"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/VLITE"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/WALLABY"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/cadc/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/ALMA"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/maq/capabilities"
    - id: "ivo://cadc.nrc.ca/CHANDRA"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/maq/capabilities"
    - id: "ivo://cadc.nrc.ca/NOAO"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/maq/capabilities"
    - id: "ivo://cadc.nrc.ca/SUBARU"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/maq/capabilities"
    - id: "ivo://cadc.nrc.ca/SDSS"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/maq/capabilities"
    - id: "ivo://cadc.nrc.ca/XMM"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/maq/capabilities"
    - id: "ivo://cadc.nrc.ca/test/ALMA"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/maq/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/ESO"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/maq/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/CHANDRA"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/maq/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/NOAO"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/maq/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/SUBARU"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/maq/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/SDSS"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/maq/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/XMM"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/maq/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/test/ASKAP"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/maq/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/ext/SKA"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/maq/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/ext/MeerKAT"
      url: "https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg/maq/sandbox/capabilities"
    - id: "ivo://cadc.nrc.ca/meetings"
      url: "https://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/meetings/capabilities"

  # Derived from IVOA Registry (reg) user interface entries in the reg-application.properties file.
  applicationEntries:
    - id: "ivo://cadc.nrc.ca/passchg"
      url: "https://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/en/auth/resetPassword.html"
    - id: "ivo://cadc.nrc.ca/passreset"
      url: "https://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/en/auth/resetPassword.html"
    - id: "ivo://cadc.nrc.ca/acctrequest"
      url: "https://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/en/auth/request.html"
    - id: "ivo://cadc.nrc.ca/acctupdate"
      url: "https://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/en/auth/update.html"
    - id: "ivo://cadc.nrc.ca/groups"
      url: "https://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/en/groups/"
    - id: "ivo://cadc.nrc.ca/login"
      url: "https://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/en/login.html"
    - id: "ivo://cadc.nrc.ca/download"
      url: "https://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/en/download"
    - id: "ivo://cadc.nrc.ca/search"
      url: "https://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/en/search"
    - id: "ivo://cadc.nrc.ca/canfar-dashboard"
      url: "https://www.canfar.net/"

ingress:
  hosts:
    - host: cadc-west-1.canfar.net
      paths:
        - path: /reg
          pathType: Prefix
