skahaWorkload:
  namespace: canfar-workloads

deployment:
  hostname: src.canfar.net
  skaha:
    posixMapperResourceID: "https://src.canfar.net/posix-mapper"
    sessions:
      hostname: workload-uv.canfar.net
