skahaWorkload:
  namespace: canfar-workloads

deployment:
  hostname: staging-src.canfar.net
  skaha:
    posixMapperResourceID: "https://staging-src.canfar.net/posix-mapper"
    sessions:
      hostname: workload-uv.staging-src.canfar.net
