metricsBackend:
  enabled: false
  env:
    METRICS_ENVIRONMENT: "staging"

deployment:
  hostname: staging-src.canfar.net
  skaha:
    image: images-rc.canfar.net/skaha-system/skaha:1.3.0-20260512T144159
    registryHosts: "images-rc.canfar.net"
    posixMapperResourceID: "https://staging-src.canfar.net/posix-mapper"
    sessions:
      hostname: workloads.canfar.net
      namespace:
        create: false
        name: canfar-workloads

      gpuEnabled: true

      kueue:
        rbac:
          create: true
        default:
          queueName: "cadc-default"
          priorityClass: "high"
        headless:
          queueName: "cadc-default"
          priorityClass: "low"

      limitRange:
        enabled: true
        create: false
        rbac:
          create: true

serviceAccount:
  create: true