ingress:
  hosts:
    - host: www.canfar.net
      paths:
        - path: /canfar
          pathType: Prefix
        - path: /cadcJS
          pathType: Prefix
        - path: /cadcVOTV
          pathType: Prefix
        - path: /vosui
          pathType: Prefix
  tls:
    - secretName: canfar-web-root-tls
      hosts:
        - www.canfar.net
