apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canfar-web-root
  namespace: argocd
  labels:
    argocd.argoproj.io/domain: canfar.net
    argocd.argoproj.io/environment: production
    argocd.argoproj.io/service: web-root
spec:
  project: default
  sources:
    - repoURL: https://images-rc.canfar.net/chartrepo/skaha-system
      chart: canfar-web-root
      targetRevision: 0.1.0
      helm:
        valueFiles:
          - $values/helm/values/canfar.net/web-root/base.yaml
          - $values/helm/values/canfar.net/web-root/prod.yaml
    - repoURL: https://git.example.com/your-org/argo-deploy.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: canfar-web-root
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
