# IVOA Registry (reg) chart defaults; see chart values:
# https://images-rc.canfar.net/chartrepo/library (chart reg).

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 8675309
  runAsGroup: 8675309
  fsGroup: 8675309
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  privileged: false
  runAsNonRoot: true
  runAsUser: 8675309
  runAsGroup: 8675309
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault

application:
  authority: "ivo://canfar.net/reg"

ingress:
  enabled: true
  className: ""
  annotations: {}
