apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: src-cavern
  namespace: canfar-argocd
  labels:
    argocd.argoproj.io/domain: src.canfar.net
    argocd.argoproj.io/environment: production
    argocd.argoproj.io/service: cavern
spec:
  project: canfar
  sources:
    - repoURL: https://images.opencadc.org/chartrepo/platform
      chart: cavern
      targetRevision: 0.9.0
      helm:
        valueFiles:
          - $values/helm/values/src.canfar.net/cavern/base.yaml
          - $values/helm/values/src.canfar.net/cavern/prod.yaml
    - repoURL: https://github.com/cadc-ccda-infra/keel-deploy.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: canfar-src-production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
