apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: src-cavern
  namespace: argocd
  labels:
    argocd.argoproj.io/domain: src.canfar.net
    argocd.argoproj.io/environment: production
    argocd.argoproj.io/service: cavern
spec:
  project: canfar
  sources:
    - repoURL: oci://harbor.example.com/src/charts
      chart: cavern
      targetRevision: 0.1.0
      helm:
        valueFiles:
          - $values/helm/values/src.canfar.net/cavern/base.yaml
          - $values/helm/values/src.canfar.net/cavern/prod.yaml
    - repoURL: https://git.example.com/your-org/argo-deploy.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: src-cavern
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
