# ClusterQueue
apiVersion: kueue.x-k8s.io/v1beta2
kind: ClusterQueue
metadata:
  name: ska
spec:
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values: [canfar-workloads]
  queueingStrategy: BestEffortFIFO
  cohortName: canfar
  # admissionScope:
  #   admissionMode: UsageBasedAdmissionFairSharing
  resourceGroups:
    - coveredResources: ["cpu", "memory", "ephemeral-storage", "nvidia.com/gpu"]
      flavors:
        - name: "default"
          resources:
            - name: "cpu"
              nominalQuota: "288"
              lendingLimit: "288"
            - name: "memory"
              nominalQuota: "1768Gi"
              lendingLimit: "1768Gi"
            - name: "ephemeral-storage"
              nominalQuota: "4500Gi"
              lendingLimit: "4500Gi"
            - name: "nvidia.com/gpu"
              nominalQuota: "28"
              lendingLimit: "28"
  preemption:
    reclaimWithinCohort: LowerPriority
    borrowWithinCohort:
      policy: LowerPriority
      maxPriorityThreshold: 10000
    withinClusterQueue: LowerPriority
  stopPolicy: None
