# ClusterQueue
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: cadc
spec:
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values: [canfar-workloads]
  queueingStrategy: BestEffortFIFO
  cohort: canfar
  resourceGroups:
    - coveredResources: ["cpu", "memory", "ephemeral-storage", "nvidia.com/gpu"]
      flavors:
        - name: "default-worker"
          resources:
            - name: "default-worker"
              nominalQuota: "2000"
              borrowingLimit: "2000"
              lendingLimit: "2000"
            - name: "memory"
              nominalQuota: "12000Gi"
              borrowingLimit: "12000Gi"
              lendingLimit: "12000Gi"
            - name: "ephemeral-storage"
              nominalQuota: "40000Gi"
              borrowingLimit: "40000Gi"
              lendingLimit: "40000Gi"
        - name: "gpu-worker"
          resources:
            - name: "cpu"
              nominalQuota: "256"
              lendingLimit: "256"
            - name: "memory"
              nominalQuota: "3000Gi"
              lendingLimit: "3000Gi"
            - name: "ephemeral-storage"
              nominalQuota: "2300Gi"
              lendingLimit: "2300Gi"
            - name: "nvidia.com/gpu"
              nominalQuota: "84"
              lendingLimit: "84"
  preemption:
    reclaimWithinCohort: LowerPriority
    borrowWithinCohort:
      policy: LowerPriority
      maxPriorityThreshold: 10000
    withinClusterQueue: LowerPriority
  stopPolicy: None
