kubernetesClusterDomain: keel-prod.local

deployment:
  hostname: www.canfar.net

  storageUI:
    registryURL:
      - "https://cadc-west-01.canfar.net/reg"

    cookieSignaturePublicKey:
      existingSecret:
        # Secret name (release namespace).
        name: cookie-signature-public-key
        # Filename under `/config` in the pod; defaults to **`RsaSignaturePub.key`** (must match Secret data entry name).
        path: RsaSignaturePub.key

    extraEnv:
      - name: CANFAR_WEB_ROOT
        value: "https://www.canfar.net"