kubernetesClusterDomain: keel-prod.local

deployment:
  hostname: staging.canfar.net

  storageUI:
    registryURL:
      - "https://staging.canfar.net/reg"

    cookieSignaturePublicKey:
      existingSecret:
        # Secret name (release namespace).
        name: canfar-skaha-staging-cookie-signature-public-key
        # Filename under `/config` in the pod; defaults to **`RsaSignaturePub.key`** (must match Secret data entry name).
        path: RsaSignaturePub.key