apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canfar-skaha-prod
  namespace: canfar-argocd
  labels:
    argocd.argoproj.io/domain: canfar.net
    argocd.argoproj.io/environment: production
    argocd.argoproj.io/service: skaha
spec:
  project: canfar
  sources:
    # - repoURL: https://images.opencadc.org/chartrepo/platform
    - repoURL: https://images-rc.canfar.net/chartrepo/skaha-system
      chart: skaha
      targetRevision: 1.7.0
      helm:
        valueFiles:
          - $values/helm/values/canfar.net/skaha/base.yaml
          - $values/helm/values/canfar.net/skaha/prod.yaml
    - repoURL: https://github.com/cadc-ccda-infra/keel-deploy.git
      targetRevision: main
      ref: values  
  destination:
    server: https://kubernetes.default.svc
    namespace: canfar-system-production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
