apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canfar-skaha-staging
  namespace: canfar-argocd
  labels:
    argocd.argoproj.io/domain: canfar.net
    argocd.argoproj.io/environment: staging
    argocd.argoproj.io/service: skaha
spec:
  project: canfar
  sources:
    - repoURL: https://images-rc.canfar.net/chartrepo/skaha-system
      chart: skaha
      targetRevision: 2.1.0
      helm:
        valueFiles:
          - $values/helm/values/canfar.net/skaha/base.yaml
          - $values/helm/values/canfar.net/skaha/staging.yaml
    - repoURL: https://github.com/cadc-ccda-infra/keel-deploy.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: canfar-system-staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
