ingress:
  hosts:
    - host: prod.canfar.net
      paths:
        - path: /citation
          pathType: Prefix

imagePullSecrets:
  - name: bucket-registry-auth

canfarWebRoot: "https://prod.canfar.net"