apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: celery-cache-pvc
  namespace: canfar-cansrc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: csi-cinder-sc-delete
  volumeMode: Filesystem
