ingress:
  enabled: true
  hosts:
    - host: canfar.cadc.dao.nrc.ca
      paths:
        - path: /access
          pathType: Prefix

registryURLs:
  - https://staging.canfar.net/reg

rsaSignaturePublicKey:
  existingSecret: rsa-signature-pub-key

serviceAccount:
  automount: false
  create: false

imagePullSecrets:
  - name: bucket-registry-auth

logging:
  groups:
    - "ivo://cadc.nrc.ca/gms?CADC"
