ingress:
  hosts:
    - host: staging.canfar.net
      paths:
        - path: /access
          pathType: Prefix

registryURLs:
  - https://staging.canfar.net/reg

rsaSignatureKeys:
  existingSecret: access-rsa-keys

imagePullSecrets:
  - name: bucket-registry-auth
