apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: canfar-system-staging-cavern-pvc
  namespace: canfar-system-staging
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: cephfs-legacy-system-staging-cavern-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: canfar-workloads-staging-pvc
  namespace: canfar-workloads
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: cephfs-legacy-workloads-staging-pv
