imagePullSecrets:
  - name: ghcr-at88mph-science-portal

ingress:
  hosts:
    - host: staging.canfar.net
      paths:
        - path: /science-portal
          pathType: Prefix

app:
  api:
    storage: "https://staging.canfar.net/arc/nodes/home/"
    skaha: "https://staging.canfar.net/skaha"
  publicApi:
    skaha: "https://staging.canfar.net/skaha"
  auth:
    nextauthUrl: "https://staging.canfar.net/science-portal"
