deployment:
  hostname: staging.canfar.net
  sciencePortal:
    registryURL: "https://staging.canfar.net/reg"
    storageHomeURL: "https://staging.canfar.net/arc/nodes/home"

    # Mount the servops certificate
    extraVolumeMounts:
      - mountPath: "/config/RsaSignaturePub.key"
        name: rsa-public-key-volume
        subPath: RsaSignaturePub.key

    # Declare the servops certificate volume to be mounted in extraVolumeMounts
    extraVolumes:
      - name: rsa-public-key-volume
        secret:
          defaultMode: 420
          secretName: access-rsa-keys