deployment:
  hostname: src.canfar.net
  cavern:
    posixMapperResourceID: "https://src.canfar.net/posix-mapper"
    resourceID: "ivo://canfar.net/src/cavern"

    loggingGroups:
      - "ivo://skao.int/gms?roles/prod/user"

    registryURL:
      - "https://reg.swesrc.chalmers.se"
      - "https://spsrc27.iaa.csic.es/reg"

    filesystem:
      dataDir: "/data"
      subPath: "cavern"
      rootOwner:
        adminUsername: "local-canfar-admin"
        username: "local-canfar-admin"
        uid: 10000
        gid: 10000

    uws:
      db:
        install: false
        maxActive: 6
        url: "jdbc:postgresql://quokka.canfar.net:8601/arcdb"
        auth:
          existingSecret: cavern-uws-db-auth
        # Postgres User default in the postgres:13 image
        runUID: 999

storage:
  service:
    spec:
      persistentVolumeClaim:
        claimName: src-cavern-pvc

# livenessProbe:
#   httpGet:
#     path: /cavern/availability
#     port: 8080
#   initialDelaySeconds: 60

# readinessProbe:
#   httpGet:
#     path: /cavern
#     port: 8080
#   initialDelaySeconds: 30
