deployment:
  hostname: staging-src.canfar.net
  cavern:
    image: images-rc.canfar.net/skaha-system/cavern:0.9.4-20260523T030950
    posixMapperResourceID: "https://staging-src.canfar.net/posix-mapper"
    resourceID: "ivo://canfar.net/staging-src/cavern"

    allocations:
      authorization:
        # permissionsAPI:
          # -- Required when enabled is true (Helm validates).
          # baseURL: "https://permissions.srcnet.skao.int/api"
          # authAPIBaseURL: "https://authn.srcnet.skao.int/api"
  
    uws:
      db:
        install: false
        maxActive: 6
        url: "jdbc:postgresql://quokka.canfar.net:8601/arcdb"
        auth:
          existingSecret: cavern-uws-db-auth
        # Postgres User default in the postgres:13 image
        runUID: 999

storage:
  service:
    spec:
      persistentVolumeClaim:
        claimName: canfar-src-cavern-pvc
