apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canfar-reg-staging
  namespace: argocd
  labels:
    argocd.argoproj.io/domain: canfar.net
    argocd.argoproj.io/environment: staging
    argocd.argoproj.io/service: reg
spec:
  project: default
  sources:
    - repoURL: https://images-rc.canfar.net/chartrepo/library
      chart: reg
      targetRevision: 1.0.0
      helm:
        valueFiles:
          - $values/helm/values/canfar.net/reg/base.yaml
          - $values/helm/values/canfar.net/reg/staging.yaml
    - repoURL: https://github.com/cadc-ccda-infra/keel-deploy.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: canfar-system-staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
