apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: canfar-workloads-cavern-pvc
  namespace: canfar-workloads
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: cephfs-static-pv